#!/bin/bash
# Build pipeline: PDF -> SVGs -> per-page G-code -> merged notebook.gcode
#
# Args:
#   $1 = path to PDF (default: pdfs/2.pdf)
#   $2 = output G-code path (default: output/notebook.gcode)
#   $3 = optional extract mode: "raster" (default) or "vector"
#   $4 = optional page order: "sequential" (default) or "spread" (unfolded signature)
# Env: PDF_TO_PRINT_PAGE_ORDER=spread (same as $4)
#
# Raster phase-1 (PDF→PNG→potrace→SVG) avoids duplicate TTF outline contours.
# Env: EXTRACT_MODE=vector | USE_VECTOR_EXTRACT=1 → inkscape vector extract.
#      USE_RASTER_EXTRACT=1 → raster (same as default; kept for scripts).
#
# Requires:
#   - .venv with vpype + vpype-gcode (or vpype on PATH)
#   - Inkscape on PATH
#   - Raster mode additionally: potrace, mkbitmap, magick (ImageMagick)
#   - ~/.vpype.toml with [gwrite.bambu_p1s_umts] (see templates/vpype_profile.toml)
#
# Reading order (Phase 2 / 2b): top-to-bottom rows, left-to-right within row.
# After portrait→landscape transform: text rows lie along gcode_X (descending), left-right along gcode_Y.
# Default axis: x (READING_FORCE_AXIS=x). Override: READING_FORCE_AXIS=y for legacy mode.
#
# Linemerge: enabled by default (merges adjacent segments → fewer pen-ups, absorbs junction noise).
# Disable: PDF_TO_PRINT_SKIP_LINEMERGE=1 ./build.sh
#
# Noise filter: strokes shorter than STROKE_MIN_LENGTH_MM (default 0.3mm) removed after tracing.
# Override: PDF_TO_PRINT_STROKE_MIN_LENGTH_MM=0.5 (raise) or =0 (disable).

set -euo pipefail

PDF="${1:-pdfs/2.pdf}"
OUT="${2:-output/notebook.gcode}"
EXTRACT="${EXTRACT_MODE:-raster}"
if [[ "${USE_RASTER_EXTRACT:-0}" == "1" ]]; then
  EXTRACT=raster
fi
if [[ "${USE_VECTOR_EXTRACT:-0}" == "1" ]]; then
  EXTRACT=vector
fi
if [[ -n "${3:-}" ]]; then
  case "$3" in
    raster) EXTRACT=raster ;;
    vector) EXTRACT=vector ;;
    *)
      echo "ERROR: third arg must be 'vector' or 'raster', got: $3" >&2
      exit 1
      ;;
  esac
fi

PAGE_ORDER="${PDF_TO_PRINT_PAGE_ORDER:-sequential}"
if [[ -n "${4:-}" ]]; then
  case "$4" in
    sequential) PAGE_ORDER=sequential ;;
    spread) PAGE_ORDER=spread ;;
    *)
      echo "ERROR: fourth arg must be 'sequential' or 'spread', got: $4" >&2
      exit 1
      ;;
  esac
fi

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

# Axis "x": text rows lie along gcode_X after portrait→landscape transform (default).
# Use READING_FORCE_AXIS=y only for legacy/debugging; invert_y is irrelevant for axis=x.
READING_FORCE_AXIS="${READING_FORCE_AXIS:-x}"
READING_OPTS=(--reading-force-axis "${READING_FORCE_AXIS}")

if [[ "${PDF_TO_PRINT_SKIP_LINEMERGE:-0}" == "1" ]]; then
  READING_OPTS+=(--skip-linemerge)
fi

# Activate venv if present
if [[ -f .venv/bin/activate ]]; then
  # shellcheck disable=SC1091
  source .venv/bin/activate
fi

# Note: ~/.vpype.toml is auto-generated by svg_to_gcode.py with Z values
# substituted from Z_PEN_DOWN / Z_HOP constants — no manual sync needed.

echo ">>> Phase 0: e2e smoke (synthetic SVG -> G-code -> strict reading-order)"
python3 scripts/e2e_reading_order_pipeline.py

echo ">>> Phase 1: extracting PDF pages to SVG (mode=$EXTRACT)"
if [[ "$EXTRACT" == "raster" ]]; then
  ./scripts/extract_pages_raster.sh "$PDF" build/svg
else
  ./scripts/extract_pages.sh "$PDF" build/svg
fi

echo ""
echo ">>> Phase 2: SVG -> per-page G-code (reading-order: axis=${READING_FORCE_AXIS}, invert_y=${PDF_TO_PRINT_READING_INVERT_Y:-1})"
python3 scripts/svg_to_gcode.py --svg-dir build/svg --out-dir build/gcode "${READING_OPTS[@]}"

echo ""
EXPERIMENTAL_OFF=1
for _exp_var in \
  PDF_TO_PRINT_EXPERIMENTAL_VARIABLE_PRESSURE \
  PDF_TO_PRINT_EXPERIMENTAL_VARIABLE_FEEDRATE \
  PDF_TO_PRINT_EXPERIMENTAL_STRIKETHROUGH; do
  case "${!_exp_var:-}" in
    1|true|yes|on) EXPERIMENTAL_OFF=0 ;;
  esac
done
if [[ "${EXPERIMENTAL_OFF}" == "0" ]]; then
  echo ">>> Phase 2b: SKIP strict reading-order validation (experimental post-process adds extra strokes)"
else
  echo ">>> Phase 2b: validate reading order (all pages, strict)"
  shopt -s nullglob
  GCODE_PAGES=(build/gcode/page_*.gcode)
  if [[ ${#GCODE_PAGES[@]} -eq 0 ]]; then
    echo "ERROR: no build/gcode/page_*.gcode after Phase 2" >&2
    exit 1
  fi
  for g in "${GCODE_PAGES[@]}"; do
    python3 scripts/validate_reading_order_gcode.py --strict --quiet "${READING_OPTS[@]}" "$g" || {
      echo "ERROR: reading-order validation failed: $g (re-run without --quiet for details)" >&2
      exit 1
    }
  done
  echo "  OK: ${#GCODE_PAGES[@]} page(s) passed reading-order + strict geometry checks"
fi

echo ""
if [[ "$PAGE_ORDER" == "spread" ]]; then
  echo ">>> Phase 3: merging pages (page order: spread — unfolded signature)"
else
  echo ">>> Phase 3: merging pages (page order: sequential)"
fi
python3 scripts/merge_pages.py --gcode-dir build/gcode --templates-dir templates --out "$OUT" \
  --page-order "$PAGE_ORDER"

echo ""
echo "✅ DONE: $OUT"
echo ""
echo "Next steps:"
echo "  1. Open Orca Slicer in LAN ONLY mode"
echo "  2. Device -> Open G-code File -> select $OUT"
echo "  3. Verify in G-code preview that all 23 pause points are present"
echo "  4. Print (operator handles UMTS install + page flips)"
