#!/bin/bash
# Build pipeline: PDF -> SVGs -> per-page G-code -> merged notebook.gcode
#
# Args:
#   $1 = path to PDF (default: pdfs/2.pdf)
#   $2 = output G-code path (default: output/notebook.gcode)
#   $3 = optional extract mode: "raster" (default) or "vector"
#
# Raster phase-1 (PDF→PNG→potrace→SVG) avoids duplicate TTF outline contours.
# Env: EXTRACT_MODE=vector | USE_VECTOR_EXTRACT=1 → inkscape vector extract.
#      USE_RASTER_EXTRACT=1 → raster (same as default; kept for scripts).
#
# Requires:
#   - .venv with vpype + vpype-gcode (or vpype on PATH)
#   - Inkscape on PATH
#   - Raster mode additionally: potrace, mkbitmap, magick (ImageMagick)
#   - ~/.vpype.toml with [gwrite.bambu_p1s_umts] (see templates/vpype_profile.toml)
#
# Reading order (Phase 2 / 2b): top-to-bottom rows, left-to-right within row — same flags on
# svg_to_gcode and validate_reading_order_gcode. Override vertical order: PDF_TO_PRINT_READING_INVERT_Y=0
# Optional: READING_FORCE_AXIS=auto|y|x (default y).
#
# Linemerge: build.sh passes --skip-linemerge by default so vpype does not fuse short skeleton
# segments into one polyline with zigzag vertex order (reading-order sort only permutes whole lines).
# Re-enable merge (fewer pen-ups, riskier path order): PDF_TO_PRINT_LINEMERGE=1

set -euo pipefail

PDF="${1:-pdfs/2.pdf}"
OUT="${2:-output/notebook.gcode}"
EXTRACT="${EXTRACT_MODE:-raster}"
if [[ "${USE_RASTER_EXTRACT:-0}" == "1" ]]; then
  EXTRACT=raster
fi
if [[ "${USE_VECTOR_EXTRACT:-0}" == "1" ]]; then
  EXTRACT=vector
fi
if [[ -n "${3:-}" ]]; then
  case "$3" in
    raster) EXTRACT=raster ;;
    vector) EXTRACT=vector ;;
    *)
      echo "ERROR: third arg must be 'vector' or 'raster', got: $3" >&2
      exit 1
      ;;
  esac
fi

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

READING_FORCE_AXIS="${READING_FORCE_AXIS:-y}"
READING_OPTS=(--reading-force-axis "${READING_FORCE_AXIS}")
case "${PDF_TO_PRINT_READING_INVERT_Y:-1}" in
  0|false|no|FALSE|NO) ;;
  *)
    READING_OPTS+=(--invert-reading-sort)
    ;;
esac

LINEMERGE_OPTS=()
if [[ "${PDF_TO_PRINT_LINEMERGE:-0}" != "1" ]]; then
  LINEMERGE_OPTS+=(--skip-linemerge)
fi

# Activate venv if present
if [[ -f .venv/bin/activate ]]; then
  # shellcheck disable=SC1091
  source .venv/bin/activate
fi

# Note: ~/.vpype.toml is auto-generated by svg_to_gcode.py with Z values
# substituted from Z_PEN_DOWN / Z_HOP constants — no manual sync needed.

echo ">>> Phase 0: e2e smoke (synthetic SVG -> G-code -> strict reading-order)"
python3 scripts/e2e_reading_order_pipeline.py

echo ">>> Phase 1: extracting PDF pages to SVG (mode=$EXTRACT)"
if [[ "$EXTRACT" == "raster" ]]; then
  ./scripts/extract_pages_raster.sh "$PDF" build/svg
else
  ./scripts/extract_pages.sh "$PDF" build/svg
fi

echo ""
echo ">>> Phase 2: SVG -> per-page G-code (reading-order: axis=${READING_FORCE_AXIS}, invert_y=${PDF_TO_PRINT_READING_INVERT_Y:-1})"
python3 scripts/svg_to_gcode.py --svg-dir build/svg --out-dir build/gcode "${READING_OPTS[@]}" "${LINEMERGE_OPTS[@]}"

echo ""
echo ">>> Phase 2b: validate reading order (all pages, strict)"
shopt -s nullglob
GCODE_PAGES=(build/gcode/page_*.gcode)
if [[ ${#GCODE_PAGES[@]} -eq 0 ]]; then
  echo "ERROR: no build/gcode/page_*.gcode after Phase 2" >&2
  exit 1
fi
for g in "${GCODE_PAGES[@]}"; do
  python3 scripts/validate_reading_order_gcode.py --strict --quiet "${READING_OPTS[@]}" "$g" || {
    echo "ERROR: reading-order validation failed: $g (re-run without --quiet for details)" >&2
    exit 1
  }
done
echo "  OK: ${#GCODE_PAGES[@]} page(s) passed reading-order + strict geometry checks"

echo ""
echo ">>> Phase 3: merging pages with wrappers"
python3 scripts/merge_pages.py --gcode-dir build/gcode --templates-dir templates --out "$OUT"

echo ""
echo "✅ DONE: $OUT"
echo ""
echo "Next steps:"
echo "  1. Open Orca Slicer in LAN ONLY mode"
echo "  2. Device -> Open G-code File -> select $OUT"
echo "  3. Verify in G-code preview that all 23 pause points are present"
echo "  4. Print (operator handles UMTS install + page flips)"
