#!/usr/bin/env python3
"""Convert SVG pages from build/svg/ into per-page G-code drawing blocks.

Pipeline per SVG:
  1. read SVG (vpype)
  2. pagerotate (CCW 90°, portrait -> landscape)
  3. scale 1 -1 around origin (flip Y, SVG-down -> Bambu-up)
  4. translate to paper origin (X=24, Y=217 — paper bottom-left in landscape coords)
  5. linemerge + linesort (path optimization)
  6. gwrite with `bambu_p1s_umts` profile (no header/footer, just G0/G1 + Z-hop)

Output: build/gcode/page_NN.gcode

Usage:
  python3 scripts/svg_to_gcode.py [--svg-dir DIR] [--out-dir DIR]

Requires:
  - Inkscape and vpype installed
  - .vpype.toml in HOME with [gwrite.bambu_p1s_umts] section (see templates/vpype_profile.toml)
"""

from __future__ import annotations

import argparse
import shutil
import subprocess
import sys
from pathlib import Path

# Pen offset relative to nozzle (firmware coords). Pen is shifted toward bed
# origin (0, 0) from nozzle position. Measured with caliper:
#   delta_X = 26.46 mm  (pen 26.46 mm toward bed-left from nozzle)
#   delta_Y = 37.9  mm  (pen 37.9 mm toward bed-front from nozzle)
# Diagonal sanity: √(26.46² + 37.9²) = 46.2 mm ≈ measured 46.5 ✓
PEN_OFFSET_X = -26.46
PEN_OFFSET_Y = -37.9

# Paper position in PEN frame (where ink lands on bed). User-friendly:
# bed-relative — measure with ruler from bed origin (front-left corner of plate).
# Constraint: paper_X_max + |PEN_OFFSET_X| ≤ 256 → paper_X_min ≤ 24.5
#             paper_Y_max + |PEN_OFFSET_Y| ≤ 256 → paper_Y_min ≤ 53.1
PAPER_LEFT  = 24.0     # mm from bed left edge to paper left
PAPER_FRONT = 50.0     # mm from bed front edge to paper front
PAPER_W     = 205.0    # tetradka landscape width (along X)
PAPER_H     = 165.0    # tetradka landscape height (along Y)

# Paper bounds (pen frame): X∈[24, 229], Y∈[50, 215]
# Nozzle bounds (gcode):    X∈[50.46, 255.46], Y∈[87.9, 252.9] ✓ within bed [0, 256]
#
# vpype `translate` target = NOZZLE frame (firmware coords). After scale 1 -1,
# content Y becomes negative; translate by paper rear edge in nozzle frame
# (paper_rear_pen + |PEN_OFFSET_Y| = 215 + 37.9 = 252.9).
PAPER_ORIGIN_X = f"{PAPER_LEFT - PEN_OFFSET_X}mm"            # 50.46
PAPER_ORIGIN_Y = f"{PAPER_FRONT + PAPER_H - PEN_OFFSET_Y}mm"  # 252.9

# Z-offset (mm) — distance pen tip extends BELOW nozzle when UMTS module loaded.
# Critical: raw G-code we generate uses absolute Z values in NOZZLE frame.
# When pen touches paper, nozzle is at Z = Z_PEN_DOWN above bed.
# When pen lifts (Z-hop), nozzle is at Z = Z_PEN_DOWN + Z_HOP.
# Source: UMTS docs §Z-Offset: +17 Stabilo, +20 POSCA. Xiaomi gel ≈ +18 (between).
# Calibrate live (Test 3 of operator-manual.md) and update here.
Z_PEN_DOWN = 18.0
Z_HOP = 3.0

VPYPE_PROFILE = "bambu_p1s_umts"
LINEMERGE_TOLERANCE = "0.1mm"


def find_vpype() -> str:
    # Prefer venv-local vpype if present
    venv = Path(__file__).resolve().parent.parent / ".venv" / "bin" / "vpype"
    if venv.exists():
        return str(venv)
    fallback = shutil.which("vpype")
    if not fallback:
        sys.exit("ERROR: vpype not found. Activate .venv or pip install vpype vpype-gcode")
    return fallback


def write_vpype_profile() -> None:
    """Write ~/.vpype.toml with Z constants substituted. Required because vpype
    gwrite reads profiles from ~/.vpype.toml — we cannot pass Z inline."""
    z_down = Z_PEN_DOWN
    z_up = Z_PEN_DOWN + Z_HOP
    content = f"""# Auto-generated by scripts/svg_to_gcode.py.
# Source of truth: Z_PEN_DOWN={Z_PEN_DOWN}, Z_HOP={Z_HOP} in svg_to_gcode.py.
# To change pen Z calibration: edit svg_to_gcode.py and re-run.

[gwrite.bambu_p1s_umts]
unit = "mm"
vertical_flip = false
document_start = ""
document_end = ""
layer_start = ""
layer_end = ""
line_start = ""
segment_first = "G0 X{{x:.3f}} Y{{y:.3f}} F18000\\nG1 Z{z_down:.3f} F1200\\n"
segment = "G1 X{{x:.3f}} Y{{y:.3f}} F12000\\n"
line_end = "G1 Z{z_up:.3f} F1200\\n"
info = "Bambu Lab P1S + UMTS pen plotter. Z_PEN_DOWN={Z_PEN_DOWN} Z_HOP={Z_HOP}"
"""
    target = Path.home() / ".vpype.toml"
    target.write_text(content)
    print(f"  wrote {target} (Z down={z_down}, Z up={z_up})")


def convert_one(vpype: str, svg: Path, out: Path) -> None:
    out.parent.mkdir(parents=True, exist_ok=True)
    # vpype command chain.
    # - pagerotate --clockwise: SVG portrait → landscape, fixes upside-down-by-X
    # - scale 1 -1: SVG Y-down → bed Y-up
    # - translate: position content at paper origin in nozzle frame
    # - linemerge: merge adjacent path segments (no reorder)
    # - NO linesort: linesort optimizes travel but reorders strokes randomly,
    #   destroying handwriting top-to-bottom reading appearance.
    #   Inkscape preserves PDF rendering order (≈ reading order) — keep it.
    args = [
        vpype,
        "read", str(svg),
        "pagerotate", "--clockwise",
        "scale", "-o", "0", "0", "--", "1", "-1",
        "translate", PAPER_ORIGIN_X, PAPER_ORIGIN_Y,
        "linemerge", "--tolerance", LINEMERGE_TOLERANCE,
        "gwrite", "-p", VPYPE_PROFILE, str(out),
    ]
    result = subprocess.run(args, capture_output=True, text=True)
    if result.returncode != 0:
        print(f"  ERROR processing {svg.name}:", file=sys.stderr)
        print(result.stderr, file=sys.stderr)
        sys.exit(result.returncode)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--svg-dir", default="build/svg",
                        help="directory with page_NN.svg (default: build/svg)")
    parser.add_argument("--out-dir", default="build/gcode",
                        help="output directory (default: build/gcode)")
    args = parser.parse_args()

    svg_dir = Path(args.svg_dir)
    out_dir = Path(args.out_dir)

    svgs = sorted(svg_dir.glob("page_*.svg"))
    if not svgs:
        sys.exit(f"ERROR: no page_*.svg in {svg_dir}")

    vpype = find_vpype()
    write_vpype_profile()

    print(f"Converting {len(svgs)} SVGs -> {out_dir}")
    for svg in svgs:
        out = out_dir / (svg.stem + ".gcode")
        print(f"  {svg.name} -> {out.name}")
        convert_one(vpype, svg, out)

    total_size = sum(p.stat().st_size for p in out_dir.glob("page_*.gcode"))
    print(f"✅ generated {len(svgs)} G-code files ({total_size/1e6:.1f} MB total)")


if __name__ == "__main__":
    main()
